version: "3"

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
